feat: add radio group
worldspawn-web/bhopguessr pull request #13
Opened 2024-08-12 07:22 UTC by Canfus

2024-08-12 19:30 UTC, worldspawn-web commented
I see that you didn't merge committed in the beginning of the current branch (you have old css files, for example).
Will merge commit by myself.

2024-08-12 19:42 UTC, worldspawn-web requested changes

2024-08-12 19:42 UTC, worldspawn-web commented on frontend/src/app/assets/index.css
Why do you still have `.css` files?

We have switched to SCSS with merging the PR:
- #12 

Fetch, make merge commits into `ui/radio-group` branch, resolve conflicts and re-request review.

2024-08-13 06:43 UTC, Canfus commented
All done

2024-08-13 11:00 UTC, worldspawn-web approved these changes

2024-08-13 17:43 UTC, merged